#!/usr/bin/env bash

if
  [[ -s "/home/ec2-user/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/environment" ]]
then
  source "/home/ec2-user/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/environment"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ec2-user/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/environment'" >&2
  exit 1
fi
